# Generated by Django 3.1.7 on 2021-04-12 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.BinaryField()),
                ('description', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=3000)),
                ('start_date', models.DateField()),
                ('real_end', models.DateField(null=True)),
                ('estimated_end_date', models.DateField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.project')),
            ],
        ),
        migrations.CreateModel(
            name='RiskImpact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impacts', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='RiskProbability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='RiskState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='RiskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RiskSubtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtype', models.CharField(max_length=255)),
                ('risk_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.risktype')),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=3000, null=True)),
                ('threat', models.CharField(max_length=1000)),
                ('starter', models.CharField(max_length=1000)),
                ('reactions', models.CharField(max_length=1000, null=True)),
                ('comment', models.CharField(max_length=1000, null=True)),
                ('start_date', models.DateField()),
                ('state_change_date', models.DateField(null=True)),
                ('reaction_date', models.DateField(null=True)),
                ('project_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.projectphase')),
                ('risk_assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('risk_impacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.riskimpact')),
                ('risk_probability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.riskprobability')),
                ('risk_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.riskstate')),
                ('risk_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.risktype')),
            ],
        ),
    ]
