# Generated by Django 3.1.7 on 2021-04-12 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='customers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='risk',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='reactions',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='starter',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='risk',
            name='threat',
            field=models.TextField(),
        ),
    ]
