# Generated by Django 3.1.7 on 2021-04-13 13:08

from django.db import migrations, models
from django.core.management.sql import emit_post_migrate_signal
from django.contrib.auth.models import Group, Permission
import logging


logger = logging.getLogger(__name__)

group_permissions = {
    'company_manager': [
        'add_company',
        'change_company',
        'delete_company',
        'view_company'
    ]
}

def add_group_permissions(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    try:
        emit_post_migrate_signal(2, False, 'default')
    except TypeError:
        emit_post_migrate_signal([], 2, False, 'default', db_alias)
    
    for group, perms in group_permissions.items():
        role, created = Group.objects.get_or_create(name=group)
        logger.info(f'{group} Group created')
        for perm in perms:
            role.permissions.add(Permission.objects.get(codename=perm))
            logger.info(f'Permitting {group} to {perm}')
        role.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions)
    ]
