# Generated by Django 3.1.7 on 2021-04-12 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210412_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='company',
        ),
        migrations.RemoveField(
            model_name='project',
            name='customers',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_manager',
        ),
        migrations.RemoveField(
            model_name='projectphase',
            name='phase_manager',
        ),
        migrations.RemoveField(
            model_name='projectphase',
            name='project',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='project_phase',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='risk_assignee',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='risk_impacts',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='risk_probability',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='risk_state',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='risk_type',
        ),
        migrations.RemoveField(
            model_name='risksubtype',
            name='risk_type',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectPhase',
        ),
        migrations.DeleteModel(
            name='Risk',
        ),
        migrations.DeleteModel(
            name='RiskImpact',
        ),
        migrations.DeleteModel(
            name='RiskProbability',
        ),
        migrations.DeleteModel(
            name='RiskState',
        ),
        migrations.DeleteModel(
            name='RiskSubtype',
        ),
        migrations.DeleteModel(
            name='RiskType',
        ),
    ]
