# Generated by Django 3.1.7 on 2021-04-15 17:47

from django.db import migrations, models
from django.core.management.sql import emit_post_migrate_signal
from django.contrib.auth.models import Group, Permission
import logging


logger = logging.getLogger(__name__)

group_permissions = {
    'company_manager': [
        # Company
        'add_company',
        'change_company',
        'delete_company',
        'view_company',
        # Project
        'add_project',
        'change_project',
        'delete_project',
        'view_project',
        # ProjectPhase
        'add_projectphase',
        'change_projectphase',
        'delete_projectphase',
        'view_projectphase',
        # Risk
        'add_risk',
        'change_risk',
        'delete_risk',
        'view_risk'
    ],
    'project_manager': [
        # Project
        'add_project',
        'change_project',
        'delete_project',
        'view_project',
        # ProjectPhase
        'add_projectphase',
        'change_projectphase',
        'delete_projectphase',
        'view_projectphase',
        # Risk
        'add_risk',
        'change_risk',
        'delete_risk',
        'view_risk'
    ],
    'phase_manager': [
        # Project
        'view_project',
        # ProjectPhase
        'view_projectphase',
        # Risk
        'add_risk',
        'change_risk',
        'delete_risk',
        'view_risk'
    ],
    'customer': [
        # Project
        'view_project',
        # ProjectPhase
        'view_projectphase',
        # Risk
        'view_risk'
    ]
}

def add_group_permissions(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    try:
        emit_post_migrate_signal(2, False, 'default')
    except TypeError:
        emit_post_migrate_signal([], 2, False, 'default', db_alias)
    
    for group, perms in group_permissions.items():
        role, created = Group.objects.get_or_create(name=group)
        logger.info(f'{group} Group created')
        for perm in perms:
            role.permissions.add(Permission.objects.get(codename=perm))
            logger.info(f'Permitting {group} to {perm}')
        role.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210413_1508'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions)
    ]
