# Generated by Django 3.1.7 on 2021-04-13 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0002_company_company_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_manager',
        ),
    ]
