# Generated by Django 3.1.7 on 2021-04-14 08:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('risk', '0004_auto_20210414_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='customers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
