# Generated by Django 3.1.7 on 2021-04-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0005_auto_20210414_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectphase',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectphase',
            name='estimated_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectphase',
            name='real_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
