# Generated by Django 3.1.7 on 2021-04-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0006_auto_20210414_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='reaction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='reactions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='state_change_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
