# Generated by Django 3.1.7 on 2021-04-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0008_auto_20210415_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='risk_impacts',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='risk_probability',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='risk_state',
        ),
        migrations.AddField(
            model_name='risk',
            name='impact',
            field=models.CharField(choices=[('VVD', 'Velmi velký dopad na projekt'), ('VD', 'Velký dopad na projekt'), ('SD', 'Střední dopad na projekt'), ('MD', 'Malý dopad na projekt'), ('VMD', 'Velmi malý dopad na projekt')], default='VMD', max_length=3),
        ),
        migrations.AddField(
            model_name='risk',
            name='probability',
            field=models.CharField(choices=[('VVP', 'Velmi vysoká pravděpodobnost'), ('VP', 'Vysoká pravděpodobnost'), ('SP', 'Střední pravděpodobnost'), ('NP', 'Nízká pravděpodobnost'), ('VNP', 'Velmi nízká pravděpodobnost')], default='VNP', max_length=3),
        ),
        migrations.AddField(
            model_name='risk',
            name='state',
            field=models.CharField(choices=[('Active', 'Aktivne'), ('Closed', 'Uzatovrene'), ('Happened', 'Prihodilo sa')], default='Happened', max_length=20),
        ),
        migrations.DeleteModel(
            name='RiskImpact',
        ),
        migrations.DeleteModel(
            name='RiskProbability',
        ),
        migrations.DeleteModel(
            name='RiskState',
        ),
    ]
