# Generated by Django 3.1.7 on 2021-04-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0010_auto_20210416_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
