# Generated by Django 3.1.7 on 2021-04-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0011_auto_20210416_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='projectphase',
            name='is_active',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
