# Generated by Django 3.1.7 on 2021-04-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0012_auto_20210416_1442'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='projectphase',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_projectphase'),
        ),
    ]
